name: zephyr

permissions: read-all

on:
  push:
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SHA: 0

jobs:
  build-in-zephyr-ci-container:
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    container: ghcr.io/zephyrproject-rtos/ci:v0.27.4
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains

    strategy:
      matrix:
        board: [nucleo_f411re] # , qemu_cortex_m3]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Initialize workspace
        run: |
          west init
          west update

      - name: Build firmware for ${{ matrix.board }}
        run: |
          west build -p always -b ${{ matrix.board }} app

      - name: Create filename prefix
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          echo "SHA=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: Prepare artifacts
        shell: bash
        run: |
          cd build/zephyr
          mkdir -p artifacts

          # No *.bin/*.hex for QEMU targets
          if [[ ! "${{ matrix.board }}" =~ qemu ]]; then
            echo "Copy HW binaries"
            mv zephyr.bin ./artifacts/zephyr-${{ env.SHA }}.bin
            mv zephyr.hex ./artifacts/zephyr-${{ env.SHA }}.hex
          fi
          mv zephyr.elf ./artifacts/zephyr-${{ env.SHA }}.elf

      - name: Save artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: build_artifacts_${{ github.run_id }}_${{ matrix.board }}
          path: |
            build/zephyr/artifacts/*
